version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: memphis-backend-prod
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    networks:
      - memphis-network
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: memphis-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - memphis-network

networks:
  memphis-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local