version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: memphis-backend-dev
    command: npm run dev
    volumes:
      - ./backend:/usr/src/app/backend
      - /usr/src/app/backend/node_modules
    ports: []
    networks:
      - memphis-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: memphis-frontend-dev
    command: npm run dev -- --host
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - memphis-network

  mongo:
    ports:
      - "27017:27017"