import * as adminService from '../../../../services/adminService';
import * as collectionService from '../../../../services/collectionService';

export const songFormConfig = {
  initialState: {
    title: '',
    artist: '',
    album: '',
    durationMs: 0,
    audioUrl: '',
    coverImage: '',
    subtitle: '',
    description: '',
    language: '',
    isrc: '',
    copyright: '',
    previewStartMs: '',
    waveformUrl: '',
    lyrics: '',
    isExplicit: false,
    releaseDate: '',
    genres: '',
    emotions: '',
    instruments: '',
    tags: [],
    analysis: {
      bpm: '',
      key: '',
      mode: 1,
      energy: '',
      danceability: '',
      acousticness: '',
      valence: '',
      loudness: '',
      instrumentalness: '',
      speechiness: '',
      liveness: '',
      timeSignature: '',
      keyConfidence: '',
      tempoConfidence: '',
      complexity: '',
      groove: '',
    },
    activityProfiles: {
      focus: '',
      study: '',
      workout: '',
      party: '',
      relaxation: '',
      creativity: '',
    },
    audioQuality: {
      codec: '',
      bitrateKbps: '',
      sampleRateHz: '',
      lossless: false,
      fileSizeBytes: '',
    },
    editorial: {
      story: '',
      productionNotes: '',
      notableSamples: '',
    },
    education: {
      theoryNotes: '',
      arrangementNotes: '',
      productionBreakdown: '',
      difficulty: '',
      techniques: '',
      tools: '',
      inspiration: '',
    },
    credits: {
      writers: '',
      producers: '',
      mastering: '',
      mixing: '',
      engineers: '',
      musicians: '',
      studio: '',
      label: '',
    },
    externalLinks: {
      spotify: '',
      youtube: '',
      soundcloud: '',
      genius: '',
      bandcamp: '',
      website: '',
    },
    sharing: {
      slug: '',
      allowSharing: true,
      canonicalUrl: '',
  }, },

  api: {
    fetchById: collectionService.fetchSongById,
    create: adminService.createSong,
    update: adminService.updateSong,
  },

  relations: {
    artists: { fetch: collectionService.fetchArtists },
    albums: { fetch: collectionService.fetchAlbums },
    tags: { fetch: adminService.fetchTags },
  },

  processDataForForm: (data) => ({
    ...data,
    artist: data.artist?._id || '',
    album: data.album?._id || '',
    releaseDate: data.releaseDate ? new Date(data.releaseDate).toISOString().split('T')[0] : '',
    genres: data.genres?.join(', ') || data.genre?.join(', ') || '',
    emotions: data.emotions?.join(', ') || '',
    instruments: data.instruments?.join(', ') || '',
    tags: data.tags?.map(t => t._id) || [],
    analysis: data.analysis || {},
    activityProfiles: data.activityProfiles || {},
    audioQuality: data.audioQuality || {},
    editorial: {
      ...data.editorial,
      notableSamples: data.editorial?.notableSamples?.join(', ') || '',
    },
    education: {
      ...data.education,
      techniques: data.education?.techniques?.join(', ') || '',
      tools: data.education?.tools?.join(', ') || '',
      inspiration: data.education?.inspiration?.join(', ') || '',
    },
    credits: {
        ...data.credits,
        writers: data.credits?.writers?.join(', ') || '',
        producers: data.credits?.producers?.join(', ') || '',
        mastering: data.credits?.mastering?.join(', ') || '',
        mixing: data.credits?.mixing?.join(', ') || '',
        engineers: data.credits?.engineers?.join(', ') || '',
        musicians: data.credits?.musicians?.join(', ') || '',
    },
    externalLinks: data.externalLinks || {},
    sharing: data.sharing || {},
  }),

  processDataForSubmit: (data) => {
    const toArray = (str) => String(str || '').split(',').map(item => item.trim()).filter(Boolean);
    const toNumberOrNull = (value) => {
      if (value === '' || value === null || value === undefined) return null;
      const number = Number(value);
      return Number.isFinite(number) ? number : null;
    };
    
    return {
      ...data,
      durationMs: Number(data.durationMs),
      previewStartMs: toNumberOrNull(data.previewStartMs),
      genres: toArray(data.genres),
      emotions: toArray(data.emotions),
      instruments: toArray(data.instruments),
      analysis: {
        ...data.analysis,
        bpm: toNumberOrNull(data.analysis.bpm),
        mode: toNumberOrNull(data.analysis.mode),
        energy: toNumberOrNull(data.analysis.energy),
        danceability: toNumberOrNull(data.analysis.danceability),
        acousticness: toNumberOrNull(data.analysis.acousticness),
        valence: toNumberOrNull(data.analysis.valence),
        loudness: toNumberOrNull(data.analysis.loudness),
        instrumentalness: toNumberOrNull(data.analysis.instrumentalness),
        speechiness: toNumberOrNull(data.analysis.speechiness),
        liveness: toNumberOrNull(data.analysis.liveness),
        keyConfidence: toNumberOrNull(data.analysis.keyConfidence),
        tempoConfidence: toNumberOrNull(data.analysis.tempoConfidence),
        complexity: toNumberOrNull(data.analysis.complexity),
        groove: toNumberOrNull(data.analysis.groove),
      },
      activityProfiles: {
        focus: toNumberOrNull(data.activityProfiles.focus),
        study: toNumberOrNull(data.activityProfiles.study),
        workout: toNumberOrNull(data.activityProfiles.workout),
        party: toNumberOrNull(data.activityProfiles.party),
        relaxation: toNumberOrNull(data.activityProfiles.relaxation),
        creativity: toNumberOrNull(data.activityProfiles.creativity),
      },
      audioQuality: {
        ...data.audioQuality,
        bitrateKbps: toNumberOrNull(data.audioQuality.bitrateKbps),
        sampleRateHz: toNumberOrNull(data.audioQuality.sampleRateHz),
        fileSizeBytes: toNumberOrNull(data.audioQuality.fileSizeBytes),
      },
      editorial: {
        ...data.editorial,
        notableSamples: toArray(data.editorial.notableSamples),
      },
      education: {
        ...data.education,
        techniques: toArray(data.education.techniques),
        tools: toArray(data.education.tools),
        inspiration: toArray(data.education.inspiration),
      },
      credits: {
        ...data.credits,
        writers: toArray(data.credits.writers),
        producers: toArray(data.credits.producers),
        mastering: toArray(data.credits.mastering),
        mixing: toArray(data.credits.mixing),
        engineers: toArray(data.credits.engineers),
        musicians: toArray(data.credits.musicians),
  } }; },

  fields: [
    { component: 'divider', label: 'Basic Information' },
    { name: 'title', label: 'Song Title', type: 'text', required: true, span: 'span-2' },
    { name: 'artist', label: 'Artist', component: 'select', optionsKey: 'artists', required: true },
    { name: 'album', label: 'Album', component: 'select', optionsKey: 'albums' },
    { name: 'releaseDate', label: 'Release Date', type: 'date' },
    { name: 'durationMs', label: 'Duration (milliseconds)', type: 'number', required: true },
    { name: 'audioUrl', label: 'Audio (URL)', type: 'url' },
    { name: 'coverImage', label: 'Song Cover Image URL', type: 'url' },
    { name: 'subtitle', label: 'Subtitle', type: 'text' },
    { name: 'language', label: 'Language', type: 'text' },
    { name: 'isrc', label: 'ISRC', type: 'text' },
    { name: 'previewStartMs', label: 'Preview Start (ms)', type: 'number' },
    { name: 'waveformUrl', label: 'Waveform URL', type: 'url' },
    { name: 'isExplicit', label: 'Explicit?', description: '(Content Warning)', component: 'checkbox' },
    { name: 'description', label: 'Short Description', component: 'textarea', rows: '3', span: 'span-2' },

    { component: 'divider', label: 'Classification' },
    { name: 'genres', label: 'Genres (Comma-Separated)', type: 'text' },
    { name: 'emotions', label: 'Emotions (Comma-Separated)', type: 'text' },
    { name: 'instruments', label: 'Instruments (Comma-Separated)', type: 'text', span: 'span-2' },
    { name: 'tags', label: 'Editorial Tags', component: 'select', optionsKey: 'tags', multiple: true, className: 'admin-form__multiselect', span: 'span-2' },

    { component: 'divider', label: 'Technical Analysis' },
    { name: 'analysis.bpm', label: 'BPM', type: 'number', span: 'span-2' },
    { name: 'analysis.key', label: 'Key (e.g., C#m, F)', type: 'text' },
    { name: 'analysis.timeSignature', label: 'Time Signature', type: 'text' },
    { name: 'analysis.energy', label: 'Energy (0.0-1.0)', type: 'number', step: '0.01' },
    { name: 'analysis.danceability', label: 'Danceability (0.0-1.0)', type: 'number', step: '0.01' },
    { name: 'analysis.acousticness', label: 'Acousticness (0.0-1.0)', type: 'number', step: '0.01' },
    { name: 'analysis.valence', label: 'Valence (Positivity, 0.0-1.0)', type: 'number', step: '0.01' },
    { name: 'analysis.instrumentalness', label: 'Instrumentalness (0.0-1.0)', type: 'number', step: '0.01' },
    { name: 'analysis.speechiness', label: 'Speechiness (0.0-1.0)', type: 'number', step: '0.01' },
    { name: 'analysis.liveness', label: 'Liveness (0.0-1.0)', type: 'number', step: '0.01' },
    { name: 'analysis.complexity', label: 'Complexity (0.0-1.0)', type: 'number', step: '0.01' },
    { name: 'analysis.groove', label: 'Groove (0.0-1.0)', type: 'number', step: '0.01' },
    { name: 'analysis.keyConfidence', label: 'Key Confidence (0.0-1.0)', type: 'number', step: '0.01' },
    { name: 'analysis.tempoConfidence', label: 'Tempo Confidence (0.0-1.0)', type: 'number', step: '0.01' },
    { name: 'analysis.loudness', label: 'Loudness (dB)', type: 'number', step: '0.01' },

    { component: 'divider', label: 'Activity Fit' },
    { name: 'activityProfiles.focus', label: 'Focus (0.0-1.0)', type: 'number', step: '0.01' },
    { name: 'activityProfiles.study', label: 'Study (0.0-1.0)', type: 'number', step: '0.01' },
    { name: 'activityProfiles.workout', label: 'Workout (0.0-1.0)', type: 'number', step: '0.01' },
    { name: 'activityProfiles.party', label: 'Party (0.0-1.0)', type: 'number', step: '0.01' },
    { name: 'activityProfiles.relaxation', label: 'Relaxation (0.0-1.0)', type: 'number', step: '0.01' },
    { name: 'activityProfiles.creativity', label: 'Creativity (0.0-1.0)', type: 'number', step: '0.01' },
    
    { component: 'divider', label: 'Editorial & Credits' },
    { name: 'editorial.story', label: 'Creative Story', component: 'textarea', rows: '3' },
    { name: 'editorial.productionNotes', label: 'Production Notes', component: 'textarea', rows: '3' },
    { name: 'editorial.notableSamples', label: 'Notable Samples (Comma-Separated)', type: 'text', span: 'span-2' },
    { name: 'education.theoryNotes', label: 'Theory Notes', component: 'textarea', rows: '3' },
    { name: 'education.arrangementNotes', label: 'Arrangement Notes', component: 'textarea', rows: '3' },
    { name: 'education.productionBreakdown', label: 'Production Breakdown', component: 'textarea', rows: '3', span: 'span-2' },
    { name: 'education.difficulty', label: 'Learning Difficulty', type: 'text' },
    { name: 'education.techniques', label: 'Techniques (Comma-Separated)', type: 'text' },
    { name: 'education.tools', label: 'Tools (Comma-Separated)', type: 'text' },
    { name: 'education.inspiration', label: 'Inspirations (Comma-Separated)', type: 'text' },
    { name: 'credits.writers', label: 'Writers (Comma-Separated)', type: 'text' },
    { name: 'credits.producers', label: 'Producers (Comma-Separated)', type: 'text' },
    { name: 'credits.mastering', label: 'Mastering (Comma-Separated)', type: 'text' },
    { name: 'credits.mixing', label: 'Mixing (Comma-Separated)', type: 'text' },
    { name: 'credits.engineers', label: 'Engineers (Comma-Separated)', type: 'text' },
    { name: 'credits.musicians', label: 'Musicians (Comma-Separated)', type: 'text' },
    { name: 'credits.studio', label: 'Studio', type: 'text' },
    { name: 'credits.label', label: 'Label', type: 'text' },

    { component: 'divider', label: 'Audio Quality' },
    { name: 'audioQuality.codec', label: 'Codec', type: 'text' },
    { name: 'audioQuality.bitrateKbps', label: 'Bitrate (kbps)', type: 'number' },
    { name: 'audioQuality.sampleRateHz', label: 'Sample Rate (Hz)', type: 'number' },
    { name: 'audioQuality.fileSizeBytes', label: 'File Size (bytes)', type: 'number' },
    { name: 'audioQuality.lossless', label: 'Lossless?', description: '(High-fidelity source)', component: 'checkbox' },
    
    { component: 'divider', label: 'External Links' },
    { name: 'externalLinks.spotify', label: 'Spotify URL', type: 'url' },
    { name: 'externalLinks.youtube', label: 'YouTube URL', type: 'url' },
    { name: 'externalLinks.soundcloud', label: 'SoundCloud URL', type: 'url' },
    { name: 'externalLinks.genius', label: 'Genius URL', type: 'url' },
    { name: 'externalLinks.bandcamp', label: 'Bandcamp URL', type: 'url' },
    { name: 'externalLinks.website', label: 'Website URL', type: 'url' },

    { component: 'divider', label: 'Sharing' },
    { name: 'sharing.slug', label: 'Share Slug', type: 'text' },
    { name: 'sharing.canonicalUrl', label: 'Canonical URL', type: 'url' },
    { name: 'sharing.allowSharing', label: 'Allow sharing?', description: '(Public share links enabled)', component: 'checkbox' },

    { component: 'divider', label: 'Lyrics' },
    { name: 'lyrics', label: 'Lyrics', component: 'textarea', rows: '10', span: 'span-2' },
], };
